/*
 * generated by Xtext 2.9.2
 */
package es.uam.sara.tfg.dsl.ui;

import com.google.inject.Injector;
import es.uam.sara.tfg.dsl.editor.ui.internal.EditorActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JRuleExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EditorActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EditorActivator.getInstance().getInjector(EditorActivator.ES_UAM_SARA_TFG_DSL_JRULE);
	}
	
}
