/**
 * generated by Xtext 2.10.0
 */
package es.uam.sara.tfg.dsl;

import es.uam.sara.tfg.dsl.JRulesStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class JRulesStandaloneSetup extends JRulesStandaloneSetupGenerated {
  public static void doSetup() {
    JRulesStandaloneSetup _jRulesStandaloneSetup = new JRulesStandaloneSetup();
    _jRulesStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
