/**
 * generated by Xtext 2.10.0
 */
package es.uam.sara.tfg.dsl;

import es.uam.sara.tfg.dsl.AbstractJRulesRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class JRulesRuntimeModule extends AbstractJRulesRuntimeModule {
}
