/*
 * generated by Xtext 2.9.2
 */
package es.uam.sara.tfg.dsl.tests

import com.google.inject.Inject
import javaRule.RuleSet
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(JRuleInjectorProvider)
class JRuleParsingTest{

	@Inject
	ParseHelper<RuleSet> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
