/**
 * generated by Xtext 2.9.2
 */
package es.uam.sara.tfg.dsl.tests;

import com.google.inject.Inject;
import es.uam.sara.tfg.dsl.tests.JRuleInjectorProvider;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)
@InjectWith(JRuleInjectorProvider.class)
@SuppressWarnings("all")
public class JRuleParsingTest {
  @Inject
  private /* ParseHelper<RuleSet> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field JRuleParsingTest.parseHelper refers to the missing type RuleSet");
  }
}
