/**
 * generated by Xtext 2.9.2
 */
package es.uam.sara.tfg.dsl.ui;

import es.uam.sara.tfg.dsl.ui.AbstractJRuleUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class JRuleUiModule extends AbstractJRuleUiModule {
  public JRuleUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
