<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="javaRule" nsURI="javaRule" nsPrefix="javaRule">
  <eClassifiers xsi:type="ecore:EClass" name="RuleSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ProjectName" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" lowerBound="1" upperBound="-1"
        eType="#//Rule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="no" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantifier" lowerBound="1"
        eType="#//Quantifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="element" lowerBound="1"
        eType="#//ElementJava"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" eType="#//Filter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="satisfy" eType="#//Or"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Quantifier">
    <eLiterals name="one" value="1"/>
    <eLiterals name="exists" value="2"/>
    <eLiterals name="all" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ElementJava">
    <eLiterals name="Package" literal="package"/>
    <eLiterals name="Class" value="1" literal="class"/>
    <eLiterals name="Interface" value="2" literal="interface"/>
    <eLiterals name="Enum" value="3" literal="enum"/>
    <eLiterals name="Method" value="4" literal="method"/>
    <eLiterals name="Attribute" value="5" literal="attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Or">
    <eStructuralFeatures xsi:type="ecore:EReference" name="op" lowerBound="1" upperBound="-1"
        eType="#//And" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And">
    <eStructuralFeatures xsi:type="ecore:EReference" name="op" lowerBound="1" upperBound="-1"
        eType="#//Satisfy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Filter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" lowerBound="1"
        eType="#//Or" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="no" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Satisfy" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="File" abstract="true" eSuperTypes="#//Satisfy"/>
  <eClassifiers xsi:type="ecore:EClass" name="Package" abstract="true" eSuperTypes="#//Satisfy"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" abstract="true" eSuperTypes="#//Satisfy"/>
  <eClassifiers xsi:type="ecore:EClass" name="isImplemented" eSuperTypes="#//Interface"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration" abstract="true" eSuperTypes="#//Satisfy"/>
  <eClassifiers xsi:type="ecore:EClass" name="Class" abstract="true" eSuperTypes="#//Satisfy"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsInheritor" eSuperTypes="#//Class #//Interface"/>
  <eClassifiers xsi:type="ecore:EClass" name="Implements" eSuperTypes="#//Class">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minInterface" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxInterface" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="2147483647"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IsExtended" eSuperTypes="#//Class #//Interface"/>
  <eClassifiers xsi:type="ecore:EClass" name="Method" abstract="true" eSuperTypes="#//Satisfy"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tamanio" eSuperTypes="#//Method"/>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//Method">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numParam" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typesParam" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constructor" eSuperTypes="#//Method"/>
  <eClassifiers xsi:type="ecore:EClass" name="Return" eSuperTypes="#//Method">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" abstract="true" eSuperTypes="#//Satisfy"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeType" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Initialize" eSuperTypes="#//Attribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="Empty" eSuperTypes="#//Package #//Method #//Class #//Interface #//Enumeration #//File">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="no" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameOperation" eSuperTypes="#//Attribute #//Class #//Method #//Package #//Interface #//Enumeration #//File">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="#//NameOperator" defaultValueLiteral="nothing"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Language" eType="#//Language"
        defaultValueLiteral="EMPTY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NameType" eSuperTypes="#//Attribute #//Class #//Method #//Package #//Interface #//Enumeration #//File">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//NameCheck"
        defaultValueLiteral="nothing"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Language">
    <eLiterals name="EMPTY"/>
    <eLiterals name="SPANISH" value="1"/>
    <eLiterals name="ENGLISH" value="2" literal="ENGLISH"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NameCheck">
    <eLiterals name="nothing"/>
    <eLiterals name="UPPER_CASE" value="1"/>
    <eLiterals name="LOWER_CASE" value="2"/>
    <eLiterals name="UPPER_CAMEL_CASE" value="3"/>
    <eLiterals name="LOWER_CAMEL_CASE" value="4"/>
    <eLiterals name="START_UPPER_CASE" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NameOperator">
    <eLiterals name="nothing"/>
    <eLiterals name="EQUAL" value="1"/>
    <eLiterals name="START" value="2"/>
    <eLiterals name="END" value="3"/>
    <eLiterals name="CONTAIN" value="4"/>
    <eLiterals name="LIKE" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaDoc" eSuperTypes="#//Attribute #//Class #//Method #//Interface #//Enumeration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="return" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="throws" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="see" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contains" eSuperTypes="#//Package #//Interface #//Enumeration #//Class #//File">
    <eStructuralFeatures xsi:type="ecore:EReference" name="which" lowerBound="1" eType="#//Rule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Modifiers" eSuperTypes="#//Attribute #//Class #//Method #//Enumeration #//Interface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blend" lowerBound="1" upperBound="-1"
        eType="#//BlendModifiers" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlendModifiers">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access" eType="#//AccessModifier"
        defaultValueLiteral="nothing"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="synchronized" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AccessModifier">
    <eLiterals name="nothing"/>
    <eLiterals name="public" value="1"/>
    <eLiterals name="protected" value="2"/>
    <eLiterals name="private" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IsGeneric" eSuperTypes="#//Class #//Interface #//Method #//Attribute"/>
</ecore:EPackage>
