<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="javaRule" nsURI="javaRule" nsPrefix="javaRule">
  <eClassifiers xsi:type="ecore:EClass" name="RuleSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ProjectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rules" lowerBound="1" upperBound="-1"
        eType="#//Rule" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" lowerBound="1"
        eType="#//Action"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="on" lowerBound="1" eType="#//Testing"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Testing">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="no" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantifier" lowerBound="1"
        eType="#//Quantifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//Element" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="satisfy" lowerBound="1"
        eType="#//Or" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And">
    <eStructuralFeatures xsi:type="ecore:EReference" name="op" lowerBound="1" upperBound="-1"
        eType="#//Satisfy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Or">
    <eStructuralFeatures xsi:type="ecore:EReference" name="op" lowerBound="1" upperBound="-1"
        eType="#//And" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Action">
    <eLiterals name="check" value="1"/>
    <eLiterals name="correct" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Quantifier">
    <eLiterals name="one" value="1"/>
    <eLiterals name="exists" value="2"/>
    <eLiterals name="all" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="element" lowerBound="1"
        eType="#//ElementJava"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" eType="#//Or" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ElementJava">
    <eLiterals name="Package" literal="package"/>
    <eLiterals name="Class" value="1" literal="class"/>
    <eLiterals name="Interface" value="2" literal="interface"/>
    <eLiterals name="Enum" value="3" literal="enum"/>
    <eLiterals name="Method" value="4" literal="method"/>
    <eLiterals name="Attribute" value="5" literal="attribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Satisfy" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Package" abstract="true" eSuperTypes="#//Satisfy"/>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" abstract="true" eSuperTypes="#//Satisfy"/>
  <eClassifiers xsi:type="ecore:EClass" name="Enumeration" abstract="true" eSuperTypes="#//Satisfy"/>
  <eClassifiers xsi:type="ecore:EClass" name="Class" abstract="true" eSuperTypes="#//Satisfy"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsInheritor" eSuperTypes="#//Class">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Implements" eSuperTypes="#//Class">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxInterface" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IsExtended" eSuperTypes="#//Class">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isExtends" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Method" abstract="true" eSuperTypes="#//Satisfy"/>
  <eClassifiers xsi:type="ecore:EClass" name="HaveConstant" eSuperTypes="#//Method"/>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Method">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parametre" eSuperTypes="#//Method">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numParam" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBigInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typesParam" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constructor" eSuperTypes="#//Method"/>
  <eClassifiers xsi:type="ecore:EClass" name="Return" eSuperTypes="#//Method">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" abstract="true" eSuperTypes="#//Satisfy"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeType" eSuperTypes="#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Initialize" eSuperTypes="#//Attribute"/>
  <eClassifiers xsi:type="ecore:EClass" name="NoEmpty" eSuperTypes="#//Package #//Method #//Class #//Interface #//Enumeration"/>
  <eClassifiers xsi:type="ecore:EClass" name="Name" eSuperTypes="#//Attribute #//Class #//Method #//Package #//Interface #//Enumeration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//NameType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//NameOperator"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Language" eType="#//Language"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Language">
    <eLiterals name="ENGLISH" literal="ENGLISH"/>
    <eLiterals name="ESPANIOL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NameType">
    <eLiterals name="upperCase" value="1"/>
    <eLiterals name="lowerCase" value="2"/>
    <eLiterals name="upperCamelCase" value="3"/>
    <eLiterals name="lowerCamelCase" value="4"/>
    <eLiterals name="startUpperCase" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NameOperator">
    <eLiterals name="like"/>
    <eLiterals name="equal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JavaDoc" eSuperTypes="#//Attribute #//Class #//Method #//Interface #//Enumeration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parametre" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="return" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="throws" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="see" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conteins" eSuperTypes="#//Package #//Interface #//Enumeration #//Class">
    <eStructuralFeatures xsi:type="ecore:EReference" name="which" lowerBound="1" eType="#//Testing"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Modifiers" eSuperTypes="#//Attribute #//Class #//Method #//Enumeration #//Interface">
    <eStructuralFeatures xsi:type="ecore:EReference" name="blend" lowerBound="1" upperBound="-1"
        eType="#//BlendModifiers" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlendModifiers">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access" eType="#//AccessModifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="final" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="synchronized" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AccessModifier">
    <eLiterals name="Default"/>
    <eLiterals name="Public" value="1"/>
    <eLiterals name="Protected" value="2"/>
    <eLiterals name="Private" value="3"/>
  </eClassifiers>
</ecore:EPackage>
