/**
 * generated by Xtext 2.10.0
 */
package es.uam.sara.tfg.dsl.scoping;

import es.uam.sara.tfg.dsl.scoping.AbstractJRulesScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class JRulesScopeProvider extends AbstractJRulesScopeProvider {
}
