/**
 * generated by Xtext 2.10.0
 */
package es.uam.sara.tfg.dsl.ui.contentassist;

import es.uam.sara.tfg.dsl.ui.contentassist.AbstractJRulesProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class JRulesProposalProvider extends AbstractJRulesProposalProvider {
}
